<?php
/**
 * GeriApp — Expected Database Schema Definition
 *
 * Shared between _check_db.php and superadmin check_db API.
 * Returns the $expected array defining tables, columns, types, keys.
 */

return [
    'planes' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'key'            => ['type'=>'varchar(30)','nullable'=>false],
            'nombre'         => ['type'=>'varchar(80)','nullable'=>false],
            'tier'           => ['type'=>"enum('basico','intermedio','empresarial','custom')",'nullable'=>false,'default'=>'basico'],
            'precio'         => ['type'=>'decimal(10,2)','nullable'=>false,'default'=>'0.00'],
            'descripcion'    => ['type'=>'varchar(255)','nullable'=>true],
            'max_residentes' => ['type'=>'int','nullable'=>true],
            'max_usuarios'   => ['type'=>'int','nullable'=>true],
            'max_instituciones' => ['type'=>'smallint unsigned','nullable'=>true],
            'max_familiares' => ['type'=>'smallint unsigned','nullable'=>true],
            'max_admin'      => ['type'=>'smallint unsigned','nullable'=>true],
            'max_cuidador'   => ['type'=>'smallint unsigned','nullable'=>true],
            'max_medico'     => ['type'=>'smallint unsigned','nullable'=>true],
            'admins_ilimitados'    => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'cuidadores_ilimitados'=> ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'medicos_ilimitados'   => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'requiere_cotizacion'  => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'solicita_tarjeta_registro' => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'trial_dias'           => ['type'=>'smallint unsigned','nullable'=>false,'default'=>'30'],
            'stripe_product_id'    => ['type'=>'varchar(100)','nullable'=>true],
            'orden'                => ['type'=>'smallint','nullable'=>false,'default'=>'0'],
            'modulos'        => ['type'=>'json','nullable'=>true],
            'activo'         => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_plan_key'=>'key','idx_plan_tier'=>'tier'],
    ],
    'instituciones' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'nombre'         => ['type'=>'varchar(150)','nullable'=>false],
            'email_admin'    => ['type'=>'varchar(150)','nullable'=>false],
            'telefono'       => ['type'=>'varchar(30)','nullable'=>true],
            'direccion'      => ['type'=>'varchar(255)','nullable'=>true],
            'timezone'       => ['type'=>'varchar(60)','nullable'=>false],
            'plan_id'        => ['type'=>'int unsigned','nullable'=>true],
            'estado'         => ['type'=>"enum('activa','trial','past_due','suspendida','archivada')",'nullable'=>false,'default'=>'trial'],
            'trial_ends_at'  => ['type'=>'date','nullable'=>true],
            'plan_vence_at'  => ['type'=>'date','nullable'=>true],
            'max_residentes' => ['type'=>'int unsigned','nullable'=>true],
            'max_usuarios'   => ['type'=>'int unsigned','nullable'=>true],
            'logo_path'      => ['type'=>'varchar(255)','nullable'=>true],
            'db_name'        => ['type'=>'varchar(80)','nullable'=>true],
            'rfc'            => ['type'=>'varchar(20)','nullable'=>true],
            'ciudad'         => ['type'=>'varchar(100)','nullable'=>true],
            'estado_inst'    => ['type'=>'varchar(60)','nullable'=>true],
            'num_camas'      => ['type'=>'smallint unsigned','nullable'=>true],
            'creado_por'     => ['type'=>'varchar(80)','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','fk_inst_plan'=>'plan_id'],
    ],
    'usuarios' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>true],
            'nombre'         => ['type'=>'varchar(120)','nullable'=>false],
            'email'          => ['type'=>'varchar(150)','nullable'=>false],
            'password_hash'  => ['type'=>'varchar(255)','nullable'=>false],
            'rol'            => ['type'=>"enum('superadmin','admin','medico','enfermero','familiar')",'nullable'=>false],
            'estado'         => ['type'=>"enum('activo','inactivo')",'nullable'=>false,'default'=>'activo'],
            'password_change_required' => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'avatar_path'    => ['type'=>'varchar(255)','nullable'=>true],
            'preferencias'   => ['type'=>'json','nullable'=>true],
            'telefono'       => ['type'=>'varchar(30)','nullable'=>true],
            'ultimo_acceso'  => ['type'=>'timestamp','nullable'=>true],
            'terms_accepted_at' => ['type'=>'timestamp','nullable'=>true],
            'privacy_version'   => ['type'=>'varchar(20)','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_usr_email'=>'email','fk_usr_inst'=>'institucion_id'],
    ],
    'usuario_instituciones' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'rol'            => ['type'=>"enum('admin','medico','enfermero','familiar')",'nullable'=>false,'default'=>'enfermero'],
            'estado'         => ['type'=>"enum('activo','inactivo')",'nullable'=>false,'default'=>'activo'],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_usr_inst'=>'usuario_id,institucion_id','fk_ui_usr'=>'usuario_id','fk_ui_inst'=>'institucion_id'],
    ],
    'login_attempts' => [
        'scope' => 'master',
        'columns' => [
            'id'        => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'email'     => ['type'=>'varchar(150)','nullable'=>false],
            'ip'        => ['type'=>'varchar(45)','nullable'=>false],
            'exitoso'   => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'creado_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_la_email'=>'email','idx_la_ip'=>'ip','idx_la_fecha'=>'creado_at'],
    ],
    'password_resets' => [
        'scope' => 'master',
        'columns' => [
            'id'         => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'email'      => ['type'=>'varchar(150)','nullable'=>false],
            'token'      => ['type'=>'varchar(100)','nullable'=>false],
            'expires_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'usado'      => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'creado_at'  => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_pr_token'=>'token','idx_pr_email'=>'email'],
    ],
    'residentes' => [
        'scope' => 'both',
        'columns' => [
            'id'                  => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'      => ['type'=>'int unsigned','nullable'=>false],
            'folio'               => ['type'=>'varchar(20)','nullable'=>true],
            'nombre'              => ['type'=>'varchar(120)','nullable'=>false],
            'apellidos'           => ['type'=>'varchar(120)','nullable'=>false],
            'fecha_nacimiento'    => ['type'=>'date','nullable'=>true],
            'sexo'                => ['type'=>"enum('M','F','Otro')",'nullable'=>true],
            'curp'                => ['type'=>'varchar(20)','nullable'=>true],
            'nss'                 => ['type'=>'varchar(20)','nullable'=>true],
            'estado_civil'        => ['type'=>'varchar(50)','nullable'=>true],
            'diagnostico'         => ['type'=>'varchar(255)','nullable'=>true],
            'alergias'            => ['type'=>'text','nullable'=>true],
            'medico_id'           => ['type'=>'int unsigned','nullable'=>true],
            'familiar_id'         => ['type'=>'int unsigned','nullable'=>true],
            'habitacion'          => ['type'=>'varchar(20)','nullable'=>true],
            'fecha_ingreso'       => ['type'=>'date','nullable'=>true],
            'estado'              => ['type'=>"enum('activo','egresado','fallecido')",'nullable'=>false,'default'=>'activo'],
            'foto_path'           => ['type'=>'varchar(255)','nullable'=>true],
            'notas'               => ['type'=>'text','nullable'=>true],
            'cuidados_especiales' => ['type'=>'text','nullable'=>true],
            'tipo_sangre'         => ['type'=>'varchar(10)','nullable'=>true],
            'contacto_nombre'     => ['type'=>'varchar(200)','nullable'=>true],
            'contacto_parentesco' => ['type'=>'varchar(100)','nullable'=>true],
            'contacto_telefono'   => ['type'=>'varchar(30)','nullable'=>true],
            'contacto_telefono2'  => ['type'=>'varchar(30)','nullable'=>true],
            'contacto_email'      => ['type'=>'varchar(200)','nullable'=>true],
            'contacto_direccion'  => ['type'=>'varchar(300)','nullable'=>true],
            'contactos_json'      => ['type'=>'text','nullable'=>true],
            'creado_at'           => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','fk_res_inst'=>'institucion_id','fk_res_medico'=>'medico_id','fk_res_familiar'=>'familiar_id','idx_res_folio'=>'folio'],
    ],
    'prescripciones' => [
        'scope' => 'both',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'residente_id'   => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'nombre'         => ['type'=>'varchar(200)','nullable'=>false],
            'dosis'          => ['type'=>'varchar(100)','nullable'=>true],
            'via'            => ['type'=>'varchar(50)','nullable'=>true],
            'frecuencia'     => ['type'=>'varchar(100)','nullable'=>true],
            'horarios'       => ['type'=>'text','nullable'=>true], // post-cifrado: era json, ahora text (ciphertext base64)
            'indicacion'     => ['type'=>'text','nullable'=>true],
            'medico_nombre'  => ['type'=>'varchar(200)','nullable'=>true],
            'activo'         => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'inicio'         => ['type'=>'date','nullable'=>true],
            'fin'            => ['type'=>'date','nullable'=>true],
            'imagen'         => ['type'=>'varchar(500)','nullable'=>true],
            'expediente_id'  => ['type'=>'int unsigned','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','fk_presc_res'=>'residente_id','fk_presc_inst'=>'institucion_id'],
    ],
    // bitacora_turnos, bitacora_entradas, bitacora_rx_administraciones,
    // historial_expedientes, historial_evoluciones, historial_documentos
    // — dropped in v1.26.0 (see migrate_drop_bitacora_historial.php)
    'configuracion' => [
        'scope' => 'master',
        'columns' => [
            'id'                => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'    => ['type'=>'int unsigned','nullable'=>false],
            'smtp_host'         => ['type'=>'varchar(150)','nullable'=>true],
            'smtp_port'         => ['type'=>'smallint unsigned','nullable'=>true],
            'smtp_usuario'      => ['type'=>'varchar(150)','nullable'=>true],
            'smtp_password'     => ['type'=>'varchar(255)','nullable'=>true],
            'smtp_encriptacion' => ['type'=>"enum('tls','ssl','ninguna')",'nullable'=>true],
            'smtp_timeout'      => ['type'=>'smallint unsigned','nullable'=>true],
            'smtp_sandbox'      => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'smtp_from_email'   => ['type'=>'varchar(150)','nullable'=>true],
            'smtp_from_nombre'  => ['type'=>'varchar(100)','nullable'=>true],
            'wa_proveedor'      => ['type'=>"enum('wasender','waapi','meta','twilio')",'nullable'=>true],
            'wa_api_key'        => ['type'=>'varchar(255)','nullable'=>true],
            'wa_instance_id'    => ['type'=>'varchar(100)','nullable'=>true],
            'wa_phone'          => ['type'=>'varchar(30)','nullable'=>true],
            'wa_activo'         => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'wa_sandbox'        => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'notif_alertas'     => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'notif_bitacora'    => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'notif_familiar'    => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'turno_mat_inicio'    => ['type'=>'varchar(5)','nullable'=>true],
            'turno_mat_fin'       => ['type'=>'varchar(5)','nullable'=>true],
            'turno_mat_siglas'    => ['type'=>'varchar(4)','nullable'=>true],
            'turno_ves_inicio'    => ['type'=>'varchar(5)','nullable'=>true],
            'turno_ves_fin'       => ['type'=>'varchar(5)','nullable'=>true],
            'turno_ves_siglas'    => ['type'=>'varchar(4)','nullable'=>true],
            'turno_noc_inicio'    => ['type'=>'varchar(5)','nullable'=>true],
            'turno_noc_fin'       => ['type'=>'varchar(5)','nullable'=>true],
            'turno_noc_siglas'    => ['type'=>'varchar(4)','nullable'=>true],
            'seg_pass_min_len'    => ['type'=>'tinyint unsigned','nullable'=>true],
            'seg_pass_expira_dias'=> ['type'=>'smallint unsigned','nullable'=>true],
            'seg_2fa'             => ['type'=>'tinyint(1)','nullable'=>true],
            'seg_timeout_sesion'  => ['type'=>'smallint unsigned','nullable'=>true],
            'seg_una_sesion'      => ['type'=>'tinyint(1)','nullable'=>true],
            'seg_log_accesos'     => ['type'=>'tinyint(1)','nullable'=>true],
            'seg_max_intentos'    => ['type'=>'tinyint unsigned','nullable'=>true],
            'seg_bloqueo_min'     => ['type'=>'smallint unsigned','nullable'=>true],
            'notif_vitales'       => ['type'=>'tinyint(1)','nullable'=>true],
            'notif_meds'          => ['type'=>'tinyint(1)','nullable'=>true],
            'notif_caida'         => ['type'=>'tinyint(1)','nullable'=>true],
            'notif_condicion'     => ['type'=>'tinyint(1)','nullable'=>true],
            'notif_canal_sistema' => ['type'=>'tinyint(1)','nullable'=>true],
            'notif_canal_email'   => ['type'=>'tinyint(1)','nullable'=>true],
            'notif_canal_wa'      => ['type'=>'tinyint(1)','nullable'=>true],
            'roles_permisos'      => ['type'=>'json','nullable'=>true],
            'ia_proveedor'      => ['type'=>'varchar(30)','nullable'=>true],
            'ia_api_key'        => ['type'=>'varchar(500)','nullable'=>true],
            'ia_modelo'         => ['type'=>'varchar(100)','nullable'=>true],
            'ia_prompt'         => ['type'=>'text','nullable'=>true],
            'ia_max_palabras'   => ['type'=>'int','nullable'=>true],
            'inst_nombre'       => ['type'=>'varchar(200)','nullable'=>true],
            'moneda'            => ['type'=>'varchar(10)','nullable'=>false],
            'timezone'          => ['type'=>'varchar(60)','nullable'=>false],
            'idioma'            => ['type'=>'varchar(10)','nullable'=>false],
            'fecha_formato'     => ['type'=>'varchar(20)','nullable'=>false],
            'app_url'           => ['type'=>'varchar(255)','nullable'=>true],
            'backup_frecuencia' => ['type'=>'varchar(20)','nullable'=>true],
            'backup_hora'       => ['type'=>'varchar(5)','nullable'=>true],
            'legal_cc_email'    => ['type'=>'varchar(200)','nullable'=>true],
            'support_phone'     => ['type'=>'varchar(30)','nullable'=>true],
            'creado_at'         => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_cfg_inst'=>'institucion_id'],
    ],
    'logs_sistema' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>true],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>true],
            'accion'         => ['type'=>'varchar(100)','nullable'=>false],
            'modulo'         => ['type'=>'varchar(50)','nullable'=>false],
            'detalle'        => ['type'=>'text','nullable'=>true],
            'ip'             => ['type'=>'varchar(45)','nullable'=>true],
            'user_agent'     => ['type'=>'varchar(255)','nullable'=>true],
            'estado'         => ['type'=>"enum('ok','warn','error','info')",'nullable'=>false,'default'=>'ok'],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','fk_log_usr'=>'usuario_id','fk_log_inst'=>'institucion_id','idx_log_fecha'=>'creado_at','idx_log_estado'=>'estado'],
    ],
    'invitaciones' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'email'          => ['type'=>'varchar(150)','nullable'=>true],
            'rol'            => ['type'=>"enum('admin','medico','enfermero','familiar')",'nullable'=>false,'default'=>'enfermero'],
            'token'          => ['type'=>'varchar(64)','nullable'=>false],
            'estado'         => ['type'=>"enum('pendiente','aceptada','expirada')",'nullable'=>false,'default'=>'pendiente'],
            'mensaje'        => ['type'=>'text','nullable'=>true],
            'residente_ids'  => ['type'=>'json','nullable'=>true],
            'nombre_sugerido'  => ['type'=>'varchar(80)','nullable'=>true],
            'apellido_sugerido'=> ['type'=>'varchar(80)','nullable'=>true],
            'telefono'         => ['type'=>'varchar(30)','nullable'=>true],
            'expires_at'     => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'creado_por'     => ['type'=>'int unsigned','nullable'=>true],
            // ── Modo multi-uso (QR para eventos/promoción) ──
            // Cuando multi_uso=1, el token NO se invalida tras el primer
            // registro: permanece válido hasta expires_at o hasta revocación
            // manual. usos_count se incrementa en cada registro exitoso para
            // auditoría. Implicación HIPAA/LFPDPPP: solo debe usarse para
            // roles sin acceso preconfigurado a PHI específica (no familiar,
            // y residente_ids debe quedar vacío).
            'multi_uso'      => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'usos_count'     => ['type'=>'int unsigned','nullable'=>false,'default'=>'0'],
            // ── Modo evento (provisioning de instituciones de prueba) ──
            // Cuando permite_nueva_institucion=1 (solo válido junto a multi_uso=1),
            // el invitado al escanear el QR puede crear una nueva institución
            // y queda como administrador. Si dias_prueba > 0, esa institución
            // se crea con estado='trial' y trial_ends_at = NOW() + dias_prueba.
            // Pensado para captación en eventos / convenciones.
            'permite_nueva_institucion' => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'dias_prueba'    => ['type'=>'smallint unsigned','nullable'=>true],
        ],
        'keys' => ['PRIMARY'=>'id','uq_inv_token'=>'token','fk_inv_inst'=>'institucion_id','fk_inv_usr'=>'creado_por','idx_inv_estado'=>'estado'],
    ],

    // Invitaciones globales generadas por Superadmin para eventos masivos.
    // No vinculan al invitado a una institución existente ni a residentes.
    // Al registrarse, el usuario crea una institución nueva y queda como admin.
    'invitaciones_geriapp' => [
        'scope' => 'master',
        'columns' => [
            'id'            => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'token'         => ['type'=>'varchar(64)','nullable'=>false],
            'plan_id'       => ['type'=>'int unsigned','nullable'=>false],
            'nombre_evento' => ['type'=>'varchar(120)','nullable'=>true],
            'estado'        => ['type'=>"enum('activa','revocada','expirada')",'nullable'=>false,'default'=>'activa'],
            'expires_at'    => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'usos_count'    => ['type'=>'int unsigned','nullable'=>false,'default'=>'0'],
            'last_used_at'  => ['type'=>'timestamp','nullable'=>true],
            'creado_por'    => ['type'=>'int unsigned','nullable'=>true],
            'creado_at'     => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'    => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_inv_geriapp_token'=>'token','fk_inv_geriapp_plan'=>'plan_id','fk_inv_geriapp_usr'=>'creado_por','idx_inv_geriapp_estado'=>'estado','idx_inv_geriapp_expira'=>'expires_at'],
    ],

    'invitaciones_geriapp_eventos' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'invitacion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'tipo'           => ['type'=>"enum('scan','registro')",'nullable'=>false],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>true],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>true],
            'ip'             => ['type'=>'varchar(45)','nullable'=>true],
            'user_agent'     => ['type'=>'varchar(255)','nullable'=>true],
            'meta'           => ['type'=>'json','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','fk_ige_inv'=>'invitacion_id','idx_ige_inv_fecha'=>'invitacion_id','idx_ige_tipo_fecha'=>'tipo','idx_ige_usuario'=>'usuario_id','idx_ige_institucion'=>'institucion_id'],
    ],

    'cuidados_registros' => [
        'scope' => 'tenant',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'residente_id'   => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>false],
            'categoria'      => ['type'=>'varchar(30)','nullable'=>false],
            'datos'          => ['type'=>'text','nullable'=>true], // post-cifrado: era json, ahora text (ciphertext base64)
            'observaciones'  => ['type'=>'text','nullable'=>true],
            'fecha'          => ['type'=>'date','nullable'=>false],
            'hora'           => ['type'=>'varchar(5)','nullable'=>false],
            'subtipo'        => ['type'=>'varchar(50)','nullable'=>true],
            'pendiente'      => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'duracion_min'   => ['type'=>'smallint','nullable'=>true],
            'verificacion_biometrica' => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'timestamp_firma'=> ['type'=>'datetime','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_cr_residente'=>'residente_id','idx_cr_fecha'=>'fecha','idx_cr_categoria'=>'categoria','idx_cr_inst_fecha'=>'institucion_id,fecha','idx_cr_subtipo'=>'subtipo','idx_cr_pendiente'=>'pendiente'],
    ],
    'cuidados_notas' => [
        'scope' => 'tenant',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'residente_id'   => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>false],
            'nota'           => ['type'=>'text','nullable'=>false],
            'imagen'         => ['type'=>'varchar(255)','nullable'=>true],
            'prioridad'      => ['type'=>"enum('normal','importante','urgente')",'nullable'=>false,'default'=>'normal'],
            'leido_por'      => ['type'=>'json','nullable'=>true],
            'fecha'          => ['type'=>'date','nullable'=>false],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_cn_inst_res_fecha'=>'institucion_id,residente_id,fecha'],
    ],
    'inventario_items' => [
        'scope' => 'tenant',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'residente_id'   => ['type'=>'int unsigned','nullable'=>true],
            'nombre'         => ['type'=>'varchar(150)','nullable'=>false],
            'tipo'           => ['type'=>"enum('medicamento','suplemento','insumo','otro')",'nullable'=>false,'default'=>'insumo'],
            'unidad'         => ['type'=>'varchar(30)','nullable'=>false],
            'stock_actual'   => ['type'=>'int','nullable'=>false,'default'=>'0'],
            'stock_minimo'   => ['type'=>'int','nullable'=>false,'default'=>'10'],
            'vencimiento'    => ['type'=>'date','nullable'=>true],
            'notas'          => ['type'=>'text','nullable'=>true],
            'activo'         => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_ii_inst'=>'institucion_id'],
    ],
    'inventario_movimientos' => [
        'scope' => 'tenant',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'item_id'        => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'tipo'           => ['type'=>"enum('entrada','salida','ajuste')",'nullable'=>false],
            'cantidad'       => ['type'=>'int','nullable'=>false],
            'residente_id'   => ['type'=>'int unsigned','nullable'=>true],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>false],
            'motivo'         => ['type'=>'varchar(255)','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_im_item'=>'item_id','idx_im_inst'=>'institucion_id'],
    ],
    'notificaciones_sistema' => [
        'scope' => 'tenant',
        'columns' => [
            'id'                 => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'     => ['type'=>'int unsigned','nullable'=>false],
            'titulo'             => ['type'=>'varchar(200)','nullable'=>false],
            'mensaje'            => ['type'=>'text','nullable'=>false],
            'tipo'               => ['type'=>"enum('info','alerta','pregunta')",'nullable'=>false,'default'=>'info'],
            'opciones_respuesta' => ['type'=>'json','nullable'=>true],
            'imagen_url'         => ['type'=>'varchar(500)','nullable'=>true],
            'activo'             => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_por'         => ['type'=>'int unsigned','nullable'=>false],
            'roles_destino'      => ['type'=>'json','nullable'=>true],
            'creado_at'          => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_ns_inst'=>'institucion_id'],
    ],
    'notificaciones_sistema_log' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'notificacion_id' => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'      => ['type'=>'int unsigned','nullable'=>false],
            'visto_at'        => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'respuesta'       => ['type'=>'text','nullable'=>true],
        ],
        'keys' => ['PRIMARY'=>'id','idx_nsl_notif'=>'notificacion_id','idx_nsl_usuario'=>'usuario_id'],
    ],
    'notificaciones_log' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'int','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'  => ['type'=>'int','nullable'=>false],
            'residente_id'    => ['type'=>'int','nullable'=>true],
            'destinatario'    => ['type'=>'varchar(255)','nullable'=>true],
            'canal'           => ['type'=>'varchar(20)','nullable'=>false,'default'=>'whatsapp'],
            'tipo'            => ['type'=>'varchar(50)','nullable'=>true],
            'mensaje'         => ['type'=>'text','nullable'=>true],
            'estado'          => ['type'=>'varchar(20)','nullable'=>false,'default'=>'enviado'],
            'error_detalle'   => ['type'=>'text','nullable'=>true],
            'fecha'           => ['type'=>'datetime','nullable'=>true],
        ],
        'keys' => ['PRIMARY'=>'id'],
    ],
    // bitacora_firmas — dropped in v1.26.0
    'residentes_estado_log' => [
        'scope' => 'master',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'residente_id'    => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'estado_anterior' => ['type'=>'varchar(30)','nullable'=>false],
            'estado_nuevo'    => ['type'=>'varchar(30)','nullable'=>false],
            'usuario_id'      => ['type'=>'int unsigned','nullable'=>true],
            'usuario_nombre'  => ['type'=>'varchar(150)','nullable'=>true],
            'nota'            => ['type'=>'text','nullable'=>true],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_estado_log_res'=>'residente_id','idx_estado_log_inst'=>'institucion_id','idx_estado_log_fecha'=>'creado_at'],
    ],
    'usuario_residentes' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'      => ['type'=>'int unsigned','nullable'=>false],
            'residente_id'    => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_usr_res'=>'usuario_id,residente_id,institucion_id','idx_ur_residente'=>'residente_id','idx_ur_inst'=>'institucion_id'],
    ],
    'push_tokens' => [
        'scope' => 'master',
        'columns' => [
            'id'          => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'  => ['type'=>'int unsigned','nullable'=>false],
            'token'       => ['type'=>'varchar(512)','nullable'=>false],
            'platform'    => ['type'=>"enum('android','ios','web')",'nullable'=>false,'default'=>'android'],
            'creado_at'   => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_push_token'=>'token','idx_pt_user'=>'usuario_id'],
    ],
    'sesiones_activas' => [
        'scope' => 'master',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'      => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>true],
            'session_id'      => ['type'=>'varchar(128)','nullable'=>false],
            'ip'              => ['type'=>'varchar(45)','nullable'=>true],
            'user_agent'      => ['type'=>'varchar(512)','nullable'=>true],
            'ultimo_acceso'   => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_session_id'=>'session_id','fk_sess_usr'=>'usuario_id','idx_sess_inst'=>'institucion_id','idx_sess_ultimo'=>'ultimo_acceso'],
    ],
    'documentos_legales' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'tipo'           => ['type'=>"enum('terminos','privacidad')",'nullable'=>false],
            'version'        => ['type'=>'varchar(20)','nullable'=>false,'default'=>'1.0'],
            'titulo'         => ['type'=>'varchar(200)','nullable'=>false],
            'contenido'      => ['type'=>'mediumtext','nullable'=>false],
            'vigente'        => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'requiere_firma' => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_por'     => ['type'=>'int unsigned','nullable'=>true],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at' => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_dl_inst_tipo'=>'institucion_id,tipo','idx_dl_vigente'=>'vigente'],
    ],
    'firmas_documentos' => [
        'scope' => 'master',
        'columns' => [
            'id'           => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'documento_id' => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'   => ['type'=>'int unsigned','nullable'=>false],
            'firma_data'   => ['type'=>'mediumtext','nullable'=>false],
            'ip'           => ['type'=>'varchar(45)','nullable'=>true],
            'user_agent'   => ['type'=>'varchar(512)','nullable'=>true],
            'firmado_at'   => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_fd_doc_usr'=>'documento_id,usuario_id','idx_fd_doc'=>'documento_id','idx_fd_usr'=>'usuario_id'],
    ],
    'arco_solicitudes' => [
        'scope' => 'master',
        'columns' => [
            'id'             => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>true],
            'tipo'           => ['type'=>"enum('acceso','rectificacion','cancelacion','oposicion')",'nullable'=>false],
            'estado'         => ['type'=>"enum('pendiente','en_proceso','completada','rechazada')",'nullable'=>false,'default'=>'pendiente'],
            'descripcion'    => ['type'=>'text','nullable'=>true],
            'respuesta'      => ['type'=>'text','nullable'=>true],
            'respondido_por' => ['type'=>'int unsigned','nullable'=>true],
            'creado_at'      => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'respondido_at'  => ['type'=>'datetime','nullable'=>true],
        ],
        'keys' => ['PRIMARY'=>'id','idx_arco_usuario'=>'usuario_id','idx_arco_estado'=>'estado','idx_arco_inst'=>'institucion_id'],
    ],
    'notas_medico' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'residente_id'    => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'      => ['type'=>'int unsigned','nullable'=>false],
            'contenido'       => ['type'=>'text','nullable'=>false],
            'adjuntos'        => ['type'=>'text','nullable'=>true],
            'recetas'         => ['type'=>'json','nullable'=>true],
            'estado'          => ['type'=>"enum('vigente','archivada')",'nullable'=>false,'default'=>'vigente'],
            'archivada_at'    => ['type'=>'datetime','nullable'=>true],
            'archivada_por'   => ['type'=>'int unsigned','nullable'=>true],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_nm_inst_res'=>'institucion_id,residente_id','idx_nm_estado'=>'estado','idx_nm_creado'=>'creado_at'],
    ],
    'alertas_medico' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'residente_id'    => ['type'=>'int unsigned','nullable'=>false],
            'registro_id'     => ['type'=>'int unsigned','nullable'=>false],
            'categoria'       => ['type'=>'varchar(30)','nullable'=>false],
            'mensaje'         => ['type'=>'text','nullable'=>true],
            'creado_por'      => ['type'=>'int unsigned','nullable'=>false],
            'visto_por'       => ['type'=>'int unsigned','nullable'=>true],
            'visto_at'        => ['type'=>'datetime','nullable'=>true],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_am_inst_res'=>'institucion_id,residente_id','idx_am_registro'=>'registro_id','idx_am_visto'=>'visto_por','idx_am_creado'=>'creado_at'],
    ],
    'expediente_docs' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id'  => ['type'=>'int unsigned','nullable'=>false],
            'residente_id'    => ['type'=>'int unsigned','nullable'=>false],
            'tipo'            => ['type'=>"enum('receta','laboratorio','imagen','interpretacion','hospitalizacion','legal','nota_enfermeria','nota_medico')",'nullable'=>false,'default'=>'receta'],
            'titulo'          => ['type'=>'varchar(255)','nullable'=>false],
            'descripcion'     => ['type'=>'text','nullable'=>true],
            'fuente'          => ['type'=>"enum('medico','familiar','residente','otro')",'nullable'=>false,'default'=>'medico'],
            'nombre_fuente'   => ['type'=>'varchar(150)','nullable'=>true],
            'especialidad'    => ['type'=>'varchar(100)','nullable'=>true],
            'fecha_documento' => ['type'=>'date','nullable'=>true],
            'archivo_nombre'  => ['type'=>'varchar(255)','nullable'=>true],
            'archivo_tipo'    => ['type'=>'varchar(50)','nullable'=>true],
            'archivo_path'    => ['type'=>'varchar(500)','nullable'=>true],
            'archivos_json'   => ['type'=>'text','nullable'=>true],
            'created_by'      => ['type'=>'int unsigned','nullable'=>false],
            'created_at'      => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'      => ['type'=>'datetime','nullable'=>true,'on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_expdoc_residente'=>'residente_id','idx_expdoc_institucion'=>'institucion_id','idx_expdoc_tipo'=>'tipo','idx_expdoc_fecha'=>'fecha_documento'],
    ],

    // ═══════════════════════════════════════════════════════════════════════
    //  BILLING / SUBSCRIPTIONS (Stripe integration) — F1
    // ═══════════════════════════════════════════════════════════════════════
    // Precios por plan (multi-divisa + mensual/anual). Cada combinación tiene
    // su propio stripe_price_id (un Price por moneda+periodo).
    'plan_precios' => [
        'scope' => 'master',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'plan_id'         => ['type'=>'int unsigned','nullable'=>false],
            'moneda'          => ['type'=>'char(3)','nullable'=>false],            // ISO 4217: MXN, USD, COP, CAD
            'periodo'         => ['type'=>"enum('mensual','anual')",'nullable'=>false,'default'=>'mensual'],
            'precio'          => ['type'=>'decimal(12,2)','nullable'=>false,'default'=>'0.00'],
            'stripe_price_id' => ['type'=>'varchar(100)','nullable'=>true],
            'activo'          => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_plan_precio'=>'plan_id,moneda,periodo','fk_pp_plan'=>'plan_id'],
    ],

    // Add-ons (asientos extra de familiar/residente que se compran sueltos).
    'addons' => [
        'scope' => 'master',
        'columns' => [
            'id'          => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'codigo'      => ['type'=>'varchar(40)','nullable'=>false],
            'nombre'      => ['type'=>'varchar(80)','nullable'=>false],
            'tipo'        => ['type'=>"enum('asiento_familiar','asiento_residente')",'nullable'=>false],
            'descripcion' => ['type'=>'varchar(255)','nullable'=>true],
            'stripe_product_id' => ['type'=>'varchar(100)','nullable'=>true],
            'activo'      => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_at'   => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'  => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_addon_codigo'=>'codigo'],
    ],

    'addon_precios' => [
        'scope' => 'master',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'addon_id'        => ['type'=>'int unsigned','nullable'=>false],
            'moneda'          => ['type'=>'char(3)','nullable'=>false],
            'periodo'         => ['type'=>"enum('mensual','anual')",'nullable'=>false,'default'=>'mensual'],
            'precio'          => ['type'=>'decimal(12,2)','nullable'=>false,'default'=>'0.00'],
            'stripe_price_id' => ['type'=>'varchar(100)','nullable'=>true],
            'activo'          => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_addon_precio'=>'addon_id,moneda,periodo','fk_ap_addon'=>'addon_id'],
    ],

    // Precio de add-ons por paquete. Si no existe una fila activa para
    // (plan_id, addon_id, moneda, periodo), billing usa addon_precios global.
    'plan_addon_precios' => [
        'scope' => 'master',
        'columns' => [
            'id'              => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'plan_id'         => ['type'=>'int unsigned','nullable'=>false],
            'addon_id'        => ['type'=>'int unsigned','nullable'=>false],
            'moneda'          => ['type'=>'char(3)','nullable'=>false],
            'periodo'         => ['type'=>"enum('mensual','anual')",'nullable'=>false,'default'=>'mensual'],
            'precio'          => ['type'=>'decimal(12,2)','nullable'=>false,'default'=>'0.00'],
            'stripe_price_id' => ['type'=>'varchar(100)','nullable'=>true],
            'activo'          => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'1'],
            'creado_at'       => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','uq_plan_addon_precio'=>'plan_id,addon_id,moneda,periodo','fk_pap_plan'=>'plan_id','fk_pap_addon'=>'addon_id'],
    ],

    // Suscripción del administrador pagador. Cubre 1..N instituciones (ver pivot).
    'suscripciones' => [
        'scope' => 'master',
        'columns' => [
            'id'                    => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'owner_user_id'         => ['type'=>'int unsigned','nullable'=>false],
            'plan_id'               => ['type'=>'int unsigned','nullable'=>false],
            'moneda'                => ['type'=>'char(3)','nullable'=>false,'default'=>'MXN'],
            'periodo'               => ['type'=>"enum('mensual','anual')",'nullable'=>false,'default'=>'mensual'],
            'stripe_customer_id'    => ['type'=>'varchar(100)','nullable'=>true],
            'stripe_subscription_id'=> ['type'=>'varchar(100)','nullable'=>true],
            'estado'                => ['type'=>"enum('trial','activa','past_due','cancelada','pausada','incompleta')",'nullable'=>false,'default'=>'trial'],
            'trial_ends_at'         => ['type'=>'datetime','nullable'=>true],
            'periodo_inicio'        => ['type'=>'datetime','nullable'=>true],
            'periodo_fin'           => ['type'=>'datetime','nullable'=>true],
            'seats_familiar_extra'  => ['type'=>'int unsigned','nullable'=>false,'default'=>'0'],
            'seats_residente_extra' => ['type'=>'int unsigned','nullable'=>false,'default'=>'0'],
            'cancel_at_period_end'  => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'metadata'              => ['type'=>'json','nullable'=>true],
            'creado_at'             => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'            => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'id',
            'uq_susc_stripe'=>'stripe_subscription_id',
            'idx_susc_owner'=>'owner_user_id',
            'idx_susc_estado'=>'estado',
            'fk_susc_plan'=>'plan_id',
        ],
    ],

    // Pivot: qué instituciones cubre cada suscripción (para validar max_instituciones).
    'suscripcion_instituciones' => [
        'scope' => 'master',
        'columns' => [
            'suscripcion_id' => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'creado_at'      => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'suscripcion_id,institucion_id',
            'idx_si_inst'=>'institucion_id',
        ],
    ],

    // Suscripción individual del rol "familiar" (cuando excede el cupo del paquete del admin).
    'suscripciones_familiar' => [
        'scope' => 'master',
        'columns' => [
            'id'                    => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_familiar_id'   => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id'        => ['type'=>'int unsigned','nullable'=>true],   // institución a la que está vinculado
            'moneda'                => ['type'=>'char(3)','nullable'=>false,'default'=>'MXN'],
            'periodo'               => ['type'=>"enum('mensual','anual')",'nullable'=>false,'default'=>'mensual'],
            'stripe_customer_id'    => ['type'=>'varchar(100)','nullable'=>true],
            'stripe_subscription_id'=> ['type'=>'varchar(100)','nullable'=>true],
            'addon_id'              => ['type'=>'int unsigned','nullable'=>true],   // FK addons (asiento_familiar)
            'estado'                => ['type'=>"enum('activa','past_due','cancelada','pausada','incompleta')",'nullable'=>false,'default'=>'incompleta'],
            'periodo_inicio'        => ['type'=>'datetime','nullable'=>true],
            'periodo_fin'           => ['type'=>'datetime','nullable'=>true],
            'cancel_at_period_end'  => ['type'=>'tinyint(1)','nullable'=>false,'default'=>'0'],
            'creado_at'             => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'            => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'id',
            'uq_sf_stripe'=>'stripe_subscription_id',
            'idx_sf_user'=>'usuario_familiar_id',
            'idx_sf_inst'=>'institucion_id',
            'idx_sf_estado'=>'estado',
        ],
    ],

    // Cache de uso de asientos por institución (evita escanear todos los tenants).
    // Actualizado por triggers/eventos al crear/eliminar residentes o aceptar familiares.
    'seats_uso' => [
        'scope' => 'master',
        'columns' => [
            'suscripcion_id'    => ['type'=>'int unsigned','nullable'=>false],
            'institucion_id'    => ['type'=>'int unsigned','nullable'=>false],
            'residentes_count'  => ['type'=>'smallint unsigned','nullable'=>false,'default'=>'0'],
            'familiares_count'  => ['type'=>'smallint unsigned','nullable'=>false,'default'=>'0'],
            'actualizado_at'    => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'suscripcion_id,institucion_id',
            'idx_su_inst'=>'institucion_id',
        ],
    ],

    // Bitácora de eventos Stripe (idempotencia + auditoría). UNIQUE en stripe_event_id evita reproceso.
    'pagos_historial' => [
        'scope' => 'master',
        'columns' => [
            'id'                       => ['type'=>'bigint unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'stripe_event_id'          => ['type'=>'varchar(100)','nullable'=>false],
            'tipo'                     => ['type'=>'varchar(60)','nullable'=>false],   // checkout.session.completed, invoice.paid, etc.
            'suscripcion_id'           => ['type'=>'int unsigned','nullable'=>true],
            'suscripcion_familiar_id'  => ['type'=>'int unsigned','nullable'=>true],
            'stripe_customer_id'       => ['type'=>'varchar(100)','nullable'=>true],
            'stripe_invoice_id'        => ['type'=>'varchar(100)','nullable'=>true],
            'monto'                    => ['type'=>'decimal(12,2)','nullable'=>true],
            'moneda'                   => ['type'=>'char(3)','nullable'=>true],
            'status'                   => ['type'=>'varchar(40)','nullable'=>true],
            'raw_payload'              => ['type'=>'longtext','nullable'=>true],       // JSON completo del evento
            'recibido_at'              => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'id',
            'uq_ph_event'=>'stripe_event_id',
            'idx_ph_susc'=>'suscripcion_id',
            'idx_ph_susc_fam'=>'suscripcion_familiar_id',
            'idx_ph_tipo'=>'tipo',
            'idx_ph_fecha'=>'recibido_at',
        ],
    ],

    // Solicitudes de cotización para plan Empresarial (paquete 7).
    'cotizaciones' => [
        'scope' => 'master',
        'columns' => [
            'id'                => ['type'=>'int unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'usuario_id'        => ['type'=>'int unsigned','nullable'=>true],
            'institucion_id'    => ['type'=>'int unsigned','nullable'=>true],
            'plan_id'           => ['type'=>'int unsigned','nullable'=>true],
            'nombre_contacto'   => ['type'=>'varchar(120)','nullable'=>false],
            'email'             => ['type'=>'varchar(150)','nullable'=>false],
            'telefono'          => ['type'=>'varchar(30)','nullable'=>true],
            'institucion_nombre'=> ['type'=>'varchar(150)','nullable'=>true],
            'num_instituciones' => ['type'=>'smallint unsigned','nullable'=>true],
            'num_residentes'    => ['type'=>'smallint unsigned','nullable'=>true],
            'num_familiares'    => ['type'=>'smallint unsigned','nullable'=>true],
            'mensaje'           => ['type'=>'text','nullable'=>true],
            'estado'            => ['type'=>"enum('nueva','contactado','cotizado','ganada','perdida','descartada')",'nullable'=>false,'default'=>'nueva'],
            'notas_internas'    => ['type'=>'text','nullable'=>true],
            'creado_at'         => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'updated_at'        => ['type'=>'timestamp','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => ['PRIMARY'=>'id','idx_cot_estado'=>'estado','idx_cot_email'=>'email','idx_cot_fecha'=>'creado_at'],
    ],

    // ── Asistente IA flotante (chat) ──────────────────────────
    // Tablas tenant. Mensajes con cifrado vía EncryptionMap.
    'chat_asistente_conv' => [
        'scope' => 'tenant',
        'columns' => [
            'id'             => ['type'=>'bigint unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>false],
            'titulo'         => ['type'=>'varchar(180)','nullable'=>true],
            'creado_at'      => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'actualizado_at' => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'id',
            'idx_chat_conv_user'=>'usuario_id,actualizado_at',
            'idx_chat_conv_inst'=>'institucion_id,actualizado_at',
        ],
    ],
    'chat_asistente_mensajes' => [
        'scope' => 'tenant',
        'columns' => [
            'id'              => ['type'=>'bigint unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'conversacion_id' => ['type'=>'bigint unsigned','nullable'=>false],
            'rol'             => ['type'=>"enum('user','assistant','system')",'nullable'=>false],
            'contenido'       => ['type'=>'mediumtext','nullable'=>true],
            'contenido_enc'   => ['type'=>'mediumblob','nullable'=>true],
            'tokens_in'       => ['type'=>'int unsigned','nullable'=>true],
            'tokens_out'      => ['type'=>'int unsigned','nullable'=>true],
            'creado_at'       => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'id',
            'idx_chat_msg_conv'=>'conversacion_id,creado_at',
            'fk_chat_msg_conv'=>'conversacion_id',
        ],
    ],
    // Memoria persistente del asistente: aprendizajes acumulados por usuario
    // y/o institución. La IA emite <recordar>...</recordar> y el backend
    // guarda aquí. Se inyectan las memorias relevantes en cada respuesta.
    'chat_asistente_memoria' => [
        'scope' => 'tenant',
        'columns' => [
            'id'             => ['type'=>'bigint unsigned','nullable'=>false,'extra'=>'auto_increment'],
            'institucion_id' => ['type'=>'int unsigned','nullable'=>false],
            'usuario_id'     => ['type'=>'int unsigned','nullable'=>true],
            'tipo'           => ['type'=>"enum('preferencia','hecho','instruccion','contexto')",'nullable'=>false,'default'=>'hecho'],
            'contenido'      => ['type'=>'text','nullable'=>true],
            'contenido_enc'  => ['type'=>'blob','nullable'=>true],
            'importancia'    => ['type'=>'tinyint unsigned','nullable'=>false,'default'=>'5'],
            'uso_count'      => ['type'=>'int unsigned','nullable'=>false,'default'=>'0'],
            'ultimo_uso_at'  => ['type'=>'datetime','nullable'=>true],
            'creado_at'      => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP'],
            'actualizado_at' => ['type'=>'datetime','nullable'=>false,'default'=>'CURRENT_TIMESTAMP','on_update'=>'CURRENT_TIMESTAMP'],
        ],
        'keys' => [
            'PRIMARY'=>'id',
            'idx_chat_mem_user'=>'institucion_id,usuario_id,importancia',
            'idx_chat_mem_inst'=>'institucion_id,importancia',
        ],
    ],
];
